version: '3'
services:

  react:
    build:
      context: .
      dockerfile: Dockerfile.react
    ports:
      - '3000:3000'
  
  db:
    build:
      context: .
      dockerfile: Dockerfile.mysql
    environment:
      - MYSQL_DATABASE='centro_de_mandos_configurable'
      - MYSQL_PASSWORD='root'
      - MYSQL_ROOT_PASSWORD='root'
    ports:
      - "3307:3306"
    volumes:
      - ./bd.sql:/docker-entrypoint-initdb.d/bd.sql

  django:
    build:
      context: .
      dockerfile: Dockerfile.django
    ports:
      - '8000:8000'
    depends_on:
      - db
  # mysql:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.mysql
  #   ports:
  #     - '3307:3307'
