# Generated by Django 4.1.1 on 2023-03-22 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Areas',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('alpha3code', models.CharField(max_length=3)),
                ('alpha2code', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Competitions',
            fields=[
                ('name', models.TextField(max_length=10000)),
                ('wyId', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('formato', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
                ('areaId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.areas')),
            ],
        ),
        migrations.CreateModel(
            name='EventId2Names',
            fields=[
                ('event2nameId', models.AutoField(primary_key=True, serialize=False)),
                ('eventId', models.PositiveSmallIntegerField()),
                ('subEventId', models.PositiveSmallIntegerField()),
                ('eventLabel', models.TextField()),
                ('subEventLabel', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('eventId', models.PositiveSmallIntegerField(null=True)),
                ('subEventId', models.PositiveSmallIntegerField(null=True)),
                ('subEventName', models.TextField()),
                ('eventName', models.TextField()),
                ('matchPeriod', models.TextField()),
                ('eventSec', models.FloatField()),
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('x1', models.PositiveSmallIntegerField()),
                ('y1', models.PositiveSmallIntegerField()),
                ('x2', models.PositiveSmallIntegerField()),
                ('y2', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('status', models.TextField()),
                ('roundId', models.PositiveSmallIntegerField()),
                ('gameWeek', models.PositiveIntegerField()),
                ('seasonId', models.PositiveSmallIntegerField()),
                ('dateUtc', models.DateTimeField()),
                ('venue', models.TextField()),
                ('wyId', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('label', models.TextField()),
                ('duration', models.TextField()),
                ('competitionId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.competitions')),
            ],
        ),
        migrations.CreateModel(
            name='Players',
            fields=[
                ('weight', models.PositiveSmallIntegerField()),
                ('firstName', models.TextField()),
                ('middleName', models.TextField()),
                ('lastName', models.TextField()),
                ('birthDate', models.DateField()),
                ('height', models.PositiveSmallIntegerField()),
                ('wyId', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('foot', models.TextField()),
                ('shortName', models.TextField()),
                ('birthAreaId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='birth_area', to='main.areas')),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('roleId', models.AutoField(primary_key=True, serialize=False)),
                ('code2', models.CharField(max_length=2)),
                ('code3', models.CharField(max_length=3)),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tags2Name',
            fields=[
                ('tagId', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('city', models.TextField()),
                ('name', models.TextField(max_length=10000)),
                ('wyId', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('officialName', models.TextField()),
                ('type', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('areaId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.areas')),
            ],
        ),
        migrations.CreateModel(
            name='TeamsData',
            fields=[
                ('teamsDataId', models.AutoField(primary_key=True, serialize=False)),
                ('scoreET', models.PositiveSmallIntegerField()),
                ('side', models.TextField()),
                ('score', models.PositiveSmallIntegerField()),
                ('scoreP', models.PositiveSmallIntegerField()),
                ('hasFormation', models.PositiveSmallIntegerField()),
                ('scoreHT', models.PositiveSmallIntegerField()),
                ('matchId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.matches')),
                ('teamId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.teams')),
            ],
        ),
        migrations.CreateModel(
            name='Substitutions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('minute', models.PositiveSmallIntegerField()),
                ('assists', models.PositiveSmallIntegerField()),
                ('playerInId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_in', to='main.players')),
                ('playerOutId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_out', to='main.players')),
                ('teamsDataId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.teamsdata')),
            ],
        ),
        migrations.AddField(
            model_name='players',
            name='currentNationalTeamId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_national_team', to='main.teams'),
        ),
        migrations.AddField(
            model_name='players',
            name='currentTeamId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_team', to='main.teams'),
        ),
        migrations.AddField(
            model_name='players',
            name='passportAreaId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passport_area', to='main.areas'),
        ),
        migrations.AddField(
            model_name='players',
            name='roleId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.roles'),
        ),
        migrations.AddField(
            model_name='matches',
            name='winnerId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.teams'),
        ),
        migrations.CreateModel(
            name='LineUp',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ownGoals', models.PositiveSmallIntegerField()),
                ('redCards', models.PositiveSmallIntegerField()),
                ('goals', models.PositiveSmallIntegerField()),
                ('yellowCards', models.PositiveSmallIntegerField()),
                ('assists', models.PositiveSmallIntegerField()),
                ('playerId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.players')),
                ('teamsDataId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.teamsdata')),
            ],
        ),
        migrations.CreateModel(
            name='EventsTags',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('eventId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.events')),
                ('tagId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.tags')),
            ],
        ),
        migrations.AddField(
            model_name='events',
            name='matchId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.matches'),
        ),
        migrations.AddField(
            model_name='events',
            name='playerId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.players'),
        ),
        migrations.AddField(
            model_name='events',
            name='teamId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.teams'),
        ),
        migrations.CreateModel(
            name='Bench',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ownGoals', models.PositiveSmallIntegerField()),
                ('redCards', models.PositiveSmallIntegerField()),
                ('goals', models.PositiveSmallIntegerField()),
                ('yellowCards', models.PositiveSmallIntegerField()),
                ('assists', models.PositiveSmallIntegerField()),
                ('playerId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.players')),
                ('teamsDataId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.teamsdata')),
            ],
        ),
    ]
