# Generated by Django 4.1.1 on 2023-07-02 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='currentNationalTeamId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='current_national_team', to='main.teams'),
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
