# Generated by Django 4.1.1 on 2023-04-20 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_areas_id_alter_bench_assists_alter_bench_goals_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sankey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form', models.CharField(max_length=10)),
                ('to', models.CharField(max_length=10)),
            ],
        ),
    ]
