# Generated by Django 4.1.1 on 2023-07-02 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_players_currentnationalteamid_delete_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='players',
            name='currentNationalTeamId',
        ),
    ]
