# Generated by Django 4.1.1 on 2023-04-26 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_sankey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bench',
            name='playerId',
        ),
        migrations.RemoveField(
            model_name='bench',
            name='teamsDataId',
        ),
        migrations.RemoveField(
            model_name='competitions',
            name='areaId',
        ),
        migrations.DeleteModel(
            name='EventId2Names',
        ),
        migrations.RemoveField(
            model_name='eventstags',
            name='eventId',
        ),
        migrations.RemoveField(
            model_name='eventstags',
            name='tagId',
        ),
        migrations.RemoveField(
            model_name='lineup',
            name='playerId',
        ),
        migrations.RemoveField(
            model_name='lineup',
            name='teamsDataId',
        ),
        migrations.DeleteModel(
            name='Sankey',
        ),
        migrations.RemoveField(
            model_name='substitutions',
            name='playerInId',
        ),
        migrations.RemoveField(
            model_name='substitutions',
            name='playerOutId',
        ),
        migrations.RemoveField(
            model_name='substitutions',
            name='teamsDataId',
        ),
        migrations.DeleteModel(
            name='Tags2Name',
        ),
        migrations.RemoveField(
            model_name='matches',
            name='competitionId',
        ),
        migrations.RemoveField(
            model_name='players',
            name='birthAreaId',
        ),
        migrations.RemoveField(
            model_name='players',
            name='passportAreaId',
        ),
        migrations.RemoveField(
            model_name='teams',
            name='areaId',
        ),
        migrations.AddField(
            model_name='events',
            name='tags',
            field=models.ManyToManyField(to='main.tags'),
        ),
        migrations.DeleteModel(
            name='Areas',
        ),
        migrations.DeleteModel(
            name='Bench',
        ),
        migrations.DeleteModel(
            name='Competitions',
        ),
        migrations.DeleteModel(
            name='EventsTags',
        ),
        migrations.DeleteModel(
            name='LineUp',
        ),
        migrations.DeleteModel(
            name='Substitutions',
        ),
    ]
